version: "3.8"
services:
  solcbt-bot:
    image: uffizzi/python:3.10-slim
    build:
      context: .
    command: python -u bot.py  # 替换为您的启动文件名
    ports:
      - target: 8000
        published: 8080
    env:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - HF_API_TOKEN=${HF_API_TOKEN}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
