name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugging Face CLI
        run: pip install huggingface_hub

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token $HF_TOKEN

      - name: Deploy to Space
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          SERVER_ID: ${{ secrets.SERVER_ID }}
        run: |
          # 设置空间名称
          SPACE_NAME="$HF_USERNAME/solcbt-therapy-bot"
          
          # 克隆空间仓库
          huggingface-cli repo create $SPACE_NAME --repo-type space --space-sdk docker --exist-ok
          git clone https://huggingface.co/spaces/$SPACE_NAME
          cd $SPACE_NAME
          
          # 复制GitHub仓库内容
          cp -r $GITHUB_WORKSPACE/* .
          
          # 提交更改
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push
          
          # 设置环境变量
          huggingface-cli space config set $SPACE_NAME \
            --env "DISCORD_TOKEN=$DISCORD_TOKEN" \
            --env "HF_API_TOKEN=$HF_API_TOKEN" \
            --env "SERVER_ID=$SERVER_ID"
          
          # 重启空间
          huggingface-cli space restart $SPACE_NAME
