name: Deploy Bot
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python main.py
