name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Configure Hugging Face CLI
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # 使用您获取的令牌
        run: huggingface-cli login --token $HF_TOKEN

      - name: Deploy to Hugging Face
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          SPACE_NAME="$HF_USERNAME/sol-cbt-therapy-bot"
          
          # 创建或更新Space
          huggingface-cli repo create $SPACE_NAME --type space -y
          
          # 上传文件
          huggingface-cli upload $SPACE_NAME \
            main.py \
            requirements.txt \
            --repo-type=space
          
          # 设置环境变量
          huggingface-cli space config set $SPACE_NAME \
            --env DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            --env HF_API_TOKEN=${{ secrets.HF_API_TOKEN }} \
            --env SERVER_ID=${{ secrets.SERVER_ID }}

          echo "Deployed to: https://huggingface.co/spaces/$SPACE_NAME"
