name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run security checks
        run: |
          pip install bandit safety
          bandit -c .bandit.yml -r . -ll
          safety check --ignore=51457 --ignore=51499

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Hugging Face CLI
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          huggingface-cli login --token $HF_TOKEN

      - name: Deploy to Hugging Face
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          SPACE_NAME="$HF_USERNAME/sol-cbt-therapy-bot"
          
          # 创建或更新 Space
          huggingface-cli repo create $SPACE_NAME --type space -y
          
          # 上传文件
          huggingface-cli upload $SPACE_NAME \
            main.py \
            requirements.txt \
            .bandit.yml \
            --repo-type=space
          
          logger.info("部署成功！Space URL: https://huggingface.co/spaces/$SPACE_NAME")
